const UI_LANG = {
    ko: {
        hira: "히라가나",
        kata: "가타카나",

        // 테마
        theme_system: "시스템 기본",
        theme_light: "라이트 모드",
        theme_dark: "다크 모드",

        // 메뉴
        menu_view: "보기 설정",
        menu_voice: "음성 설정",
        menu_sec: "섹션 설정",
        menu_flash: "플래시 설정",
        menu_lang: "언어 변경",
        menu_data: "데이터 관리",
        menu_feedback: "피드백 및 제안",

        // 보기 설정
        view_bookmark: "북마크만 보기",
        view_ko: "한글 발음 표시",
        view_ruby: "대응 문자 표시",
        view_compact: "화면 축소(단축)",

        // 음성 설정
        voice_click: "클릭 시 재생",
        voice_flash: "플래시 공개 시 재생",

        // 플래시 설정
        flash_speed_fast: "빠르게",
        flash_speed_normal: "보통",
        flash_speed_slow: "느리게",
        flash_manual: "수동 모드",

        voice_normal: "보통 속도",
        voice_slow: "느리게 재생",

        // 섹션
        sec_base: "청음",
        sec_daku: "탁음",
        sec_yoon: "요음",
        sec_soku: "촉음",
        sec_choo: "장음",

        // 데이터 관리
        data_export_set: "설정 백업",
        data_export_bm: "북마크 백업",
        data_export_all: "전체 백업",
        data_import: "데이터 복구",
        data_reset_set: "설정 초기화",
        data_reset_bm: "북마크 초기화",
        data_reset_all: "전체 초기화",

        // 피드백
        fb_title: "문의 및 피드백",
        fb_type_bug: "버그 제보",
        fb_type_feedback: "피드백",
        fb_type_suggest: "기능 제안",
        fb_placeholder_subject: "제목을 입력하세요",
        fb_placeholder_msg: "내용을 입력하세요",
        fb_send: "전송",
        fb_cancel: "취소",

        // 알림
        notice_title: "알림",
        reset_confirm_title: "초기화 확인",
        thanks_msg: "성공적으로 전송되었습니다.\n소중한 의견 감사합니다!",
        empty_error: "내용을 입력해 주세요.",
        send_error: "전송 중 오류가 발생했습니다.",
        reset_set_msg: "화면 보기 및 섹션 설정을 초기화할까요?",
        reset_bm_msg: "저장된 북마크를 모두 삭제할까요?",
        reset_all_msg: "모든 데이터와 설정을 처음 상태로 되돌릴까요?",
        empty_msg: "표시할 카드가 없습니다.",

        // 단축어
        hira_short: "히라",
        kata_short: "가타"
    },

    en: {
        hira: "Hiragana",
        kata: "Katakana",
        theme_system: "System Default",
        theme_light: "Light Mode",
        theme_dark: "Dark Mode",
        menu_view: "View Settings",
        menu_voice: "Voice Settings",
        menu_sec: "Section Settings",
        menu_flash: "Flash Settings",
        menu_lang: "Change Language",
        menu_data: "Data Management",
        menu_feedback: "Feedback",
        view_bookmark: "Bookmarks Only",
        view_ko: "Show Korean",
        view_ruby: "Corresponding Character",
        view_compact: "Compact View",

        voice_click: "Play on Click",
        voice_flash: "Play on Flash",
        flash_speed_fast: "Fast",
        flash_speed_normal: "Normal",
        flash_speed_slow: "Slow",
        flash_manual: "Manual Mode",
        voice_normal: "Normal Speed",
        voice_slow: "Slow Speed",
        sec_base: "Main",
        sec_daku: "Dakuon",
        sec_yoon: "Yoon",
        sec_soku: "Sokuon",
        sec_choo: "Choon",
        data_export_set: "Export Settings",
        data_export_bm: "Export Bookmarks",
        data_export_all: "Export All",
        data_import: "Import Data",
        data_reset_set: "Reset Settings",
        data_reset_bm: "Reset Bookmarks",
        data_reset_all: "Reset All",
        fb_title: "Feedback",
        fb_type_bug: "Bug Report",
        fb_type_feedback: "Feedback",
        fb_type_suggest: "Suggestion",
        fb_placeholder_subject: "Enter subject",
        fb_placeholder_msg: "Enter message",
        fb_send: "Send",
        fb_cancel: "Cancel",
        notice_title: "Notice",
        reset_confirm_title: "Confirm Reset",
        thanks_msg: "Sent successfully.\nThank you for your feedback!",
        empty_error: "Please enter your message.",
        send_error: "An error occurred.",
        reset_set_msg: "Reset display and section settings?",
        reset_bm_msg: "Delete all bookmarks?",
        reset_all_msg: "Reset everything?",
        empty_msg: "No cards to display.",

        hira_short: "Hira",
        kata_short: "Kata"
    },

    ja: {
        hira: "ひらがな",
        kata: "カタカナ",
        theme_system: "システム既定",
        theme_light: "ライトモード",
        theme_dark: "ダークモード",
        menu_view: "表示設定",
        menu_voice: "音声設定",
        menu_sec: "セクション設定",
        menu_flash: "フラッシュ設定",
        menu_lang: "言語変更",
        menu_data: "データ管理",
        menu_feedback: "フィードバック",
        view_bookmark: "ブックマークのみ",
        view_ko: "ハングル表示",
        view_ruby: "対応文字表示",
        view_compact: "コンパクト表示",

        voice_click: "クリック時再生",
        voice_flash: "フラッシュ時再生",
        flash_speed_fast: "速く",
        flash_speed_normal: "普通",
        flash_speed_slow: "ゆっくり",
        flash_manual: "手動モード",
        voice_normal: "通常速度",
        voice_slow: "ゆっくり再生",
        sec_base: "清音",
        sec_daku: "濁音",
        sec_yoon: "拗音",
        sec_soku: "促音",
        sec_choo: "長音",
        data_export_set: "設定をバックアップ",
        data_export_bm: "ブックマークをバックアップ",
        data_export_all: "全体バックアップ",
        data_import: "データ復元",
        data_reset_set: "設定を初期化",
        data_reset_bm: "ブックマークを初期化",
        data_reset_all: "全体初期化",
        fb_title: "フィードバック",
        fb_type_bug: "バグ報告",
        fb_type_feedback: "フィードバック",
        fb_type_suggest: "機能提案",
        fb_placeholder_subject: "件名を入力",
        fb_placeholder_msg: "内容を入力",
        fb_send: "送信",
        fb_cancel: "キャンセル",
        notice_title: "通知",
        reset_confirm_title: "初期化の確認",
        thanks_msg: "送信に成功しました。\nご意見ありがとうございます！",
        empty_error: "内容を入力してください。",
        send_error: "送信中にエラーが発生しました。",
        reset_set_msg: "表示とセクション設定を初期化しますか？",
        reset_bm_msg: "すべてのブックマークを削除しますか？",
        reset_all_msg: "すべてを初期状態に戻しますか？",
        empty_msg: "表示するカードがありません。",

        hira_short: "ひら",
        kata_short: "カタ"
    }
};